apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: webapi-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: us-central1-docker.pkg.dev/project1-444610/jenkins-project/pn1-dotnet-api:1 # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: webapi-ssvc
  namespace: webapps
spec:
  selector:
    app: webapi
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer # type of the service.
